# Generated by Django 5.1.3 on 2024-12-11 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la promoción')),
                ('descripcion', models.TextField(verbose_name='Descripción de la promoción')),
                ('descuento', models.IntegerField(verbose_name='Descuento (%)')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin de la promoción')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromocionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uso_promociones', to='examenApp.promocion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uso_promociones', to='examenApp.usuario')),
            ],
            options={
                'unique_together': {('promocion', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='promocion',
            name='usuarios',
            field=models.ManyToManyField(related_name='promociones', through='examenApp.PromocionUsuario', to='examenApp.usuario', verbose_name='Usuarios asignados'),
        ),
    ]
