# Generated by Django 5.1.3 on 2024-12-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='producto',
            new_name='productos',
        ),
        migrations.RenameField(
            model_name='promocion',
            old_name='usuario',
            new_name='usuarios',
        ),
    ]
